### ISSUE TITLE
Find out why media views showing as 0

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#672] opened 2019-10-31 09:47 UTC
I noticed this in the LMH server, so not sure if it's one of the following options (or a combination):
bug in the activity log upload

- difference in the ids/digests 
- due to differences in the courses being used on devices vs the course on the server
- related to this issue in the app: https://github.com/DigitalCampus/oppia-mobile-android/issues/904

Note that this issue occurs for users who do have a lot of media views (with media completed) in their activity log files - so I don't think it's just to do with the user not having completed any media activities.

**Comment by alexlittle** [comment] 2019-11-19 11:49
As an example, this user has all the activities showing as completed, but they haven't watched any videos, so unclear how they can have the activities complete.

![Screenshot from 2019-11-19 13-46-07](https://user-images.githubusercontent.com/344917/69144186-665d7700-0ad3-11ea-9eb4-a3ad49ff28f5.png)

**Comment by jjoseba** [comment] 2019-11-25 12:22
I spent time looking at the trackers for different users based on the trackers table and the activity logs, querying the database in search for specific digests. I found what the problem was but I was not understanding how could that be happening, and not being able to reproduce it. 

At the end, the problem was not specifically a server-side problem, but an app one. The server had no media trackers saved for those courses, but had a lot of trackers with event data related with media views that had an activity digest, and therefore were being marked as a "page" activity instead.
The misleading part is that it was a problem we had already detected and fixed (it was solved in this PR: https://github.com/DigitalCampus/oppia-mobile-android/pull/791), so in the current version of the app is solved, but I was not realizing that the activity logs are generated in an old version of the app.

Once this was identified, the solution was to take into account this trackers in the calculation of media views. For this to be reflected in the summaries, they have to be recalculated from the beginning (using the `update_summaries` command with the `--fromstart` parameter).

**Closed** 2019-11-25 13:03 UTC
Labels: bug, est-8-hours, high priority
